kubevela/velad

- util.go
> Fix: temp file not found

- .github/workflows/e2e-test.yaml
- Makefile
> Feat: add e2e-test

- Makefile
- README.md
Signed-off-by: barnettZQG <barnett.zqg@gmail.com>
> Feat: upgrade the version to 1.4.2

- pkg/cluster/k3d.go
Fixes: https://github.com/kubevela/velad/issues/28
> Fix: generate kubeconfig in Windows

- docs/contribute.md
- pkg/cmd/cli.go
- pkg/utils/util.go
> Fix: can't connect to cluster if set network proxy

- docs/05.expose-cluster.md
Fixes: https://github.com/kubevela/velad/issues/33
> Doc: add expose doc

- pkg/apis/types.go
- pkg/cluster/handler.go
- pkg/cluster/k3d.go
- pkg/cluster/k3s.go
- pkg/cmd/command.go
- pkg/cmd/control.go
- pkg/utils/util.go
- pkg/vela/kubevela.go
> Feat: add dry-run option for velad install

- docs/01.simple.md
- docs/06.develop_kubevela.md
fixes: https://github.com/kubevela/velad/issues/10
> Doc: add develop KubeVela using VelaD doc

- docs/05.expose-cluster.md
> Doc: update expose doc for secure group

- .autorc
- .github/workflows/auto-release.yaml
- .gitignore
**How is this tested**: 
I test this auto release workflow in this [repo](https://github.com/chivalryq/test-auto-release)
> Chore: add auto release based on PR labels

- .github/workflows/build.yaml
- .github/workflows/e2e-test.yaml
- .github/workflows/release.yml
- Makefile
- hack/download_k3d_images.sh
- hack/download_vela_images.sh
- pkg/cluster/k3d.go
- pkg/cluster/k3s.go
> Feat: add linux-arm64 release

- hack/install-velad.sh
> Fix: remove unsupported platform in install script

- docs/07.using-gateway-trait.md
> Doc: access service in cluster

- Makefile
- go.mod
- go.sum
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/apply-application-in-parallel.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/apply-application.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/apply-object.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/apply-once.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/apply-remaining.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/depends-on-app.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/deploy-cloud-resource.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/deploy.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/deploy2env.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/deploy2runtime.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/envbinding.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/export2config.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/export2secret.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/notification.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/override.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/read-object.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/step-group.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/suspend.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/topology.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/webhook.yaml
- pkg/resources/static/vela/charts/vela-core/templates/test/test-application.yaml
> Feat: bump vela to v1.5.0-beta.2

- .github/workflows/release.yml
- hack/install-velad.ps1
> Fix: release download dependency with wrong arch

- pkg/utils/util.go
> Fix: better kubeconfig guide in windows

- Makefile
- go.mod
- go.sum
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
> Bump vela to v1.5.3

- Makefile
- go.mod
- go.sum
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
- pkg/resources/static/vela/charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- pkg/resources/static/vela/charts/vela-core/crds/core.oam.dev_applications.yaml
- pkg/resources/static/vela/charts/vela-core/crds/core.oam.dev_traitdefinitions.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/cron-task.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/daemon.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/deploy2runtime.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/gateway.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/notification.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/service-account.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/storage.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/task.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/volumes.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/webhook-notification.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/webservice.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/worker.yaml
> Bump vela to v1.6.0-alpha.1

- Makefile
- go.mod
- go.sum
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/topology.yaml
- pkg/resources/static/vela/charts/vela-core/templates/test/test-application.yaml
Hold until this is merged: https://github.com/kubevela/catalog/pull/458
> Bump vela to 1.5.4

- hack/download_k3d_images.sh
- pkg/apis/types.go
> Backport: Fix: wrong cached k3s-tool image

- Makefile
- go.mod
- go.sum
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/webservice.yaml
> Bump vela to v1.5.5

- Makefile
- go.mod
- go.sum
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
- pkg/resources/static/vela/charts/vela-core/templates/kubevela-controller.yaml
> Bump vela to v1.5.6

- Makefile
- go.mod
- go.sum
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/gateway.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/init-container.yaml
> Bump vela to v1.5.7 (#80)

- .github/workflows/e2e-test.yaml
- Makefile
- go.mod
- go.sum
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
> Bump vela to v1.5.8 & add velaux enabling test

- Makefile
- contribute/upgrade-vela.md
- go.mod
- go.sum
- hack/upgrade_vela.sh
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/apply-application-in-parallel.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/apply-application.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/apply-remaining.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/deploy-cloud-resource.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/deploy.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/deploy2env.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/deploy2runtime.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/share-cloud-resource.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/webservice.yaml
> Bump vela to v1.6.1, more automation

- Makefile
- go.mod
- go.sum
- hack/upgrade_vela.sh
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
> Bump vela to 1.6.3, allow empty patch

- Makefile
- go.mod
- go.sum
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
> Bump vela to v1.6.5

- Makefile
- go.mod
- go.sum
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
- pkg/resources/static/vela/charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- pkg/resources/static/vela/charts/vela-core/crds/core.oam.dev_applications.yaml
> Bump vela to v1.7.0-beta.2

- go.mod
- go.sum
> Fix: wrongly replaced k3d modules

- pkg/cluster/k3d.go
- pkg/loadbalancer/loadbalancer.go
- pkg/utils/docker.go
- pkg/utils/util.go
Signed-off-by: fengshunli <1171313930@qq.com>
> Fix: remove outdated ioutil references

- hack/download_k3d_images.sh
Signed-off-by: fengshunli <1171313930@qq.com>
> Fix: interception failed

- pkg/vela/kubevela.go
Signed-off-by: fengshunli <1171313930@qq.com>
> Fix: comment format

- .github/workflows/e2e-test.yaml
> Feat: add argument to e2e for testing air-gap installation capability

- .github/workflows/code-lint.yaml
- makefiles/dependency.mk
- pkg/cluster/k3d.go
- pkg/utils/docker.go
- pkg/utils/util.go
- test/e2e-test/ingress_test.go
- test/e2e-test/suite_test.go
> Fix: code lint CI

- Makefile
- go.mod
- go.sum
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
- pkg/resources/static/vela/charts/vela-core/README.md
> Feat: bump vela to v1.7.1

- Makefile
- go.mod
- go.sum
- pkg/resources/static/vela/charts/vela-core/Chart.yaml
- pkg/resources/static/vela/charts/vela-core/templates/defwithtemplate/notification.yaml
> Bump vela to v1.7.3

- Makefile
- go.mod
- go.sum
Fixes: https://github.com/kubevela/velad/issues/156
> Chore: upgrade vela to v1.9.5
